---
- name: Verify VMs are Configured
  hosts: local
  gather_facts: False
  tasks:
    - name: set fact with hostnames
      set_fact: foo_item="{{ item.value.hostname }}"
      with_dict: nodes
      register: foo_result

    - name: make a list
      set_fact: nodes_list="{{ foo_result.results | map(attribute='ansible_facts.foo_item') | list }}"

    - debug: var=nodes_list

    - name: Wait for puppet to complete
      foreman_validate:
        foreman_url: "{{ provisioner.foreman_url }}"
        foreman_username: "{{ provisioner.username }}"
        foreman_password: "{{ provisioner.password }}"
        node_list: "{{ nodes_list }}"